info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-19T03:26:35.973Z"}
info: Connected to the database. {"timestamp":"2022-02-19T03:26:39.432Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-19T03:34:17.202Z"}
error: 
    status - 500 
    message - ValidationError: "name" is required 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-19T03:39:39.038Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T04:11:01.656Z"}
info: Connected to the database. {"timestamp":"2022-02-21T04:11:06.643Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T04:18:27.148Z"}
info: Connected to the database. {"timestamp":"2022-02-21T04:18:32.665Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T07:54:21.130Z"}
info: Connected to the database. {"timestamp":"2022-02-21T07:54:21.538Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T08:15:42.735Z"}
info: Connected to the database. {"timestamp":"2022-02-21T08:15:42.788Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:57:01.480Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:57:01.538Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:05:58.988Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:05:59.067Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T16:18:59.747Z"}
info: Connected to the database. {"timestamp":"2022-02-21T16:18:59.819Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T16:34:56.858Z"}
info: Connected to the database. {"timestamp":"2022-02-21T16:34:56.933Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T16:42:56.871Z"}
info: Connected to the database. {"timestamp":"2022-02-21T16:42:56.911Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/userregister 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-21T16:45:05.627Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/userregister 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-21T16:46:01.483Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: user.users index: email_1 dup key: { email: "vishnu@gamail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::1
     {"timestamp":"2022-02-21T16:46:23.641Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\build\middlewares\error.middleware.js:43:26)
    at Layer.handle_error (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:321:13)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T16:46:23.652Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/userregister 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-21T16:46:48.783Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/userregister 
      method - GET 
      IP - ::1
     {"timestamp":"2022-02-21T16:47:00.889Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: user.users index: email_1 dup key: { email: "vishnu@gamail.com" } 
      url - /api/v1/users/userregister 
      method - POST 
      IP - ::1
     {"timestamp":"2022-02-21T16:51:28.749Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\response.js:267:15)
    at appErrorHandler (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\build\middlewares\error.middleware.js:43:26)
    at Layer.handle_error (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:321:13)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:341:12)
    at Immediate.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\express\lib\router\index.js:641:15)
    at processImmediate (node:internal/timers:466:21) 
    url - /api/v1/users/userregister 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T16:51:28.753Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T03:01:47.367Z"}
info: Connected to the database. {"timestamp":"2022-02-22T03:01:47.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T03:03:17.521Z"}
info: Connected to the database. {"timestamp":"2022-02-22T03:03:17.559Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T03:09:59.539Z"}
info: Connected to the database. {"timestamp":"2022-02-22T03:09:59.592Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:25:40.272Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:25:40.319Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:37:08.630Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:37:08.711Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:42:46.295Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:42:46.330Z"}
error: 
    status - 500 
    message - TypeError: user is not a function
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:14)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T04:44:51.732Z"}
error: 
    status - 500 
    message - TypeError: user is not a function
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:14)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T04:45:22.117Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:24:11)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T04:47:00.323Z"}
error: 
    status - 500 
    message - TypeError: user is not a function
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:14)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T04:47:14.352Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T04:51:11.623Z"}
info: Connected to the database. {"timestamp":"2022-02-22T04:51:11.683Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:00:53.491Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:00:53.555Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'findOne')
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:22:27)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:21:19)
    at _callee4$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\controllers\/user.controller.js:63:36)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T05:01:03.978Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:01:26.256Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:01:26.374Z"}
error: 
    status - 500 
    message - TypeError: user is not a function
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:14)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T05:02:47.968Z"}
error: 
    status - 500 
    message - TypeError: user is not a function
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:29:14)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T05:20:09.251Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:24:52.389Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:24:52.460Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:32:12.785Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:32:12.843Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T05:44:37.195Z"}
info: Connected to the database. {"timestamp":"2022-02-22T05:44:37.229Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:10:57.068Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:10:57.120Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:24:11)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T11:15:15.329Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:24:11)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T11:17:06.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:18:30.205Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:18:30.279Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:26:03.441Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:26:03.486Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:27:30.347Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:27:30.381Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:29:22.865Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:29:22.936Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:31:08.055Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:31:08.129Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:21:22)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T11:31:16.399Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:21:22)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T11:31:37.385Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:32:42.250Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:32:42.283Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:24:11)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T11:32:47.644Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-22T11:41:05.774Z"}
info: Connected to the database. {"timestamp":"2022-02-22T11:41:05.854Z"}
error: 
    status - 500 
    message - Error: password is invalid
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:35:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-22T11:43:22.006Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-23T02:33:16.846Z"}
info: Connected to the database. {"timestamp":"2022-02-23T02:33:16.895Z"}
error: 
    status - 500 
    message - Error: User does not exist
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:24:11)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-23T04:02:21.790Z"}
error: 
    status - 500 
    message - Error: password is invalid
    at _callee3$ (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\src\services\/user.service.js:35:13)
    at tryCatch (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\VISHNU SATHEESH\Project\Fundoo-Notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-02-23T04:02:39.262Z"}
